<a href="https://colab.research.google.com/github/MrSaurabh0028/Bca-data-science-projects/blob/main/R_language_r.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

R Languages

In [ ]:
#simple program for R language.
print("Hello")
x<-"How are"
print(x)
cat("you","\n")
# addition
x<-10
y<-20
cat("sum is:",x+y,"\n")
#muti
a<-20
b<-5
cat("muti is:",a*b)
#User-define
a<-as.numeric(readline("Enter first number:"))
b<-as.numeric(readline("Enter second number:"))
cat("total multiply:",a*b)

[1] "Hello"
[1] "How are"
you 
sum is: 30 
muti is: 100Enter first number:4
Enter second number:5
total multiply: 20

 **1) if and else statements**

In [ ]:
a<-100
b<-52
if(a>b){
 cat(a,"is greater.")
}else{
cat(b,"is greater.")
}
#user define
cat("\n")
a<-as.numeric(readline("Enter first number:"))
b<-as.numeric(readline("Enter second number:"))
if(a>b){
  cat(a,"is greater.")
}else if(a==b){
  cat("both are qural.")
}else{
  cat(b,"is grater.")
}

100 is greater.
Enter first number:20
Enter second number:20
both are qural.

In [ ]:
#3 user input
a<-as.numeric(readline("Enter first number:"))
b<-as.numeric(readline("Enter second number:"))
c<-as.numeric(readline("Enter third number:"))
if(a>b && a>c){
  cat(a,"is greater.")
}else if(b>a && b>c){
  cat(b,"is greater.")
}else if(a==b && b==c && c==a){
  cat("all are equal.")
}else{
  cat(c,"is greater.")
}

Enter first number:2
Enter second number:2
Enter third number:2
all are equal.

In [ ]:
# positive aur negative number
a<--20
if(a>0){
  cat(a,"is positive number.")
}else{
  cat(a,"is negative number.")
}
#user input
cat("\n")
first<-as.numeric(readline("Enter a number:"))
if(first>0){
  cat(first,"is positive number.")
}else if(first==0){
  cat(first,"is not positive or negative number.")
}else{
  cat(first,"is negative number.")
}

-20 is negative number.
Enter a number:0
0 is not positive or negative number.

In [ ]:
#student matrks (If else)
std<-as.numeric(readline("Enter your marks 1 to 100:"))
if(std>100){
  cat("invalid number.")
}else if(std>=85){
 cat("Grade: A")
}else if(std>=75){
  cat("Grade B.")
}else if(std>=65){
  cat("grade c.")
}else if(std>=1){
  cat("fail.")
}

Enter your marks 1 to 100:85
Grade: A

In [ ]:
# ager related (if else)
age<-as.numeric(readline("Enter age between 0 to 85:"))
if(age>85){
  cat("invalid age.")
}else if(age>=60){
  cat("Senior Citizen.")
}else if(age>=20){
  cat("Adult.")
}else if(age>=13){
  cat("Teen age.")
}else{
  cat("child.")
}

Enter age between 0 to 85:86
invalid age.

In [ ]:
#check even number and it divisible by 5.
a<-as.numeric(readline("Enter a number:"))
if(a%%2==0){
  cat("even number.","\n")
   if(a%%5==0){
    cat("divisible by 5.")
   }else{
    cat("not divisibl by 5.")
   }
}else{
  cat("odd number")
}

Enter a number:420
even number. 
divisible by 5.

***For Loop***

In [ ]:
#print 1 to 10(for loop)
for(i in 1:10)
cat(i,"\n")
# Even or odd number using(for loop)
for(i in 1:50){
 if(i%%2==0){
  cat(i,"even number","\n")
 }else{
  cat(i,"odd number.")
 }
}

1 odd number.2 even number 
3 odd number.4 even number 
5 odd number.6 even number 
7 odd number.8 even number 
9 odd number.10 even number 
11 odd number.12 even number 
13 odd number.14 even number 
15 odd number.16 even number 
17 odd number.18 even number 
19 odd number.20 even number 
21 odd number.22 even number 
23 odd number.24 even number 
25 odd number.26 even number 
27 odd number.28 even number 
29 odd number.30 even number 
31 odd number.32 even number 
33 odd number.34 even number 
35 odd number.36 even number 
37 odd number.38 even number 
39 odd number.40 even number 
41 odd number.42 even number 
43 odd number.44 even number 
45 odd number.46 even number 
47 odd number.48 even number 
49 odd number.50 even number 


In [ ]:
#print 1 to 10 and their sum.
sum<-0
for(i in(1:10)){
  sum<-sum+i
}
cat("total sum is:",sum)    # total print lop ke bahar aana padta haiii.

total sum is: 55

In [ ]:
#factorial number.
fact<-1
a<-as.numeric(readline("Enter a number:"))
for(i in(1:a)){
 fact<-fact*i
}
cat("total factotial is:",fact)

Enter a number:5
total factotial is: 120

In [ ]:
num <- as.numeric(readline("Enter a positive number: "))

# Initialize variables
count <- 0
sum <- 0
reverse <- 0
temp <- num

while(temp > 0){
  digit <- temp %% 10                           # extract last digit
  sum <- sum + digit                            # add to sum
  reverse <- reverse * 10 + digit               # build reverse
  count <- count + 1                            # count digits
  temp <- temp %/% 10                           # remove last digit
}

cat("Digits count:", count, "\n")
cat("Sum of digits:", sum, "\n")
cat("Reverse of number:", reverse, "\n")


Enter a positive number: 52
Digits count: 2 
Sum of digits: 7 
Reverse of number: 25 


***Arrays ***
arrays are the data objects which allow us to store data in more than two dimension.

In [ ]:
a <- array(1:20, dim = c(2, 3, 2))
cat(a)           #Linear or simple output.
b<-array(1:20,dim=c(2,3,2)) #dim=c(2=row,3=col,2=page/box),c = vactor
print(b)           # Multi-dimension structured.
c<-array(1:11,dim=c(2,4,2))
print(c)

1 2 3 4 5 6 7 8 9 10 11 12, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

, , 2

     [,1] [,2] [,3] [,4]
[1,]    9   11    2    4
[2,]   10    1    3    5



***Matrix***

In [ ]:
a<-matrix(c(40,50,60,70,80,90,20,30,50),nrow=3,ncol=3)
print(a)
cat("second row:",a[2, ],"\n")
cat("third col:",a[ ,3],"\n")
cat("first col of third elements:",a[1,3])

     [,1] [,2] [,3]
[1,]   40   70   20
[2,]   50   80   30
[3,]   60   90   50
second row: 50 80 30 
third col: 20 30 50 
first col of third elements: 20

In [ ]:
fruit<-factor(c("apple","mango","grapes","mango","apple","banana","apple","banana"))
cat(fruit,"\n")    #show indexing.
print(fruit)  # show level of factor.

1 4 3 4 1 2 1 2 
[1] apple  mango  grapes mango  apple  banana apple  banana
Levels: apple banana grapes mango


***Function***

.....piece of code that is used again and again.

In [ ]:
fun<-function(){   # function ka name and function()key word.but (py)me (def)
  for (i in 1:5){
    cat("i am learnin function","\n")
  }
}
fun()

i am learnin function 
i am learnin function 
i am learnin function 
i am learnin function 
i am learnin function 


In [ ]:
# function with parameter(square number)
fun<-function(a){
  cat("square is:",a^2)
}

a<-as.numeric(readline("Enter a number:"))
fun(a)

Enter a number:5
square is: 25

In [ ]:
fun<-function(a){
  if(a>=0){
    cat(a,"is positive number.","\n")
      if(a%%2==0){
        cat(a,"even number.")
      }else{
        cat(a,"odd number.")
      }
  }else{
    cat(a,"is negative number.")
  }
}
a<-as.numeric(readline("Enter a number:"))
fun(a)

Enter a number:45
45 is positive number. 
45 odd number.

In [ ]:
# grade a,b,c,b,d
fun<-function(a){
  if(a>=85){
    cat("grade A.")
  }else if(a>=75){
    cat("grade B.")
  }else if(a>=65){
    cat("Grade C")
  }else{
    cat("Fail")
  }
}
a<-as.numeric(readline("Enter a number:"))
fun(a)

Enter a number:0
Fail

In [ ]:
# Function + Percentage + Grade
fun<-function(a,b,c){
  tm<-a+b+c
  per<-(tm/300)*100
  cat("total marks is:",tm,"\n")
  cat("percentage:",per,"%","\n")
  if(per>=85){
    cat("Grade A")
  }else if(per>=75){
    cat("Grade B")
  }else if(per>=65){
    cat("Grade C")
  }else{
    cat("fail")
  }
}


a<-as.numeric(readline("Enter maths marks:"))
b<-as.numeric(readline("Enter science marks:"))
c<-as.numeric(readline("Enter english marks:"))
fun(a,b,c)

Enter maths marks:45
Enter science marks:45
Enter english marks:5
total marks is: 95 
percentage: 31.66667 % 
fail

In [ ]:
# Function + Percentage + Grade
fun<-function(a,b,c,name){
  tm<-a+b+c
  per<-(tm/300)*100
  cat(name)
  cat("total marks is:",tm,"\n")
  cat("percentage:",per,"%","\n")
  if(per>=85){
    cat("Grade A")
  }else if(per>=75){
    cat("Grade B")
  }else if(per>=65){
    cat("Grade C")
  }else{
    cat("fail")
  }
}
for (i in 1:3) {            # colab me loop me hi stuck ho gaya hai
  cat("\n","student details",i,"\n")#but r studio me chal raha hai ye code.

  name <- readline("Enter student name: ")
  a<-as.numeric(readline("Enter maths marks:"))
  b<-as.numeric(readline("Enter science marks:"))
  c<-as.numeric(readline("Enter english marks:"))
  fun(a,b,c,name)
}

***File Handling***

✅ CSV files	read.csv(), read.table()	Base R

✅ Excel files	read_excel()	readxl or openxlsx

✅ JSON files	fromJSON()	jsonlite

✅ XML files	xmlParse()	XML

✅ Web Data	readLines(), rvest	rvest

✅ Databases	dbConnect(), dbReadTable()	RMySQL, RSQLite, etc.

In [6]:
# file handling(csv.file)        # run on r studio.
getwd()     #to know the file existences.
setwd("C://Users//91620//OneDrive//Desktop") #to set the path of file/directory
file.exists("C://Users//91620//OneDrive//Desktop//file.csv") # to check fil is exist or not
file.exists("file.csv")

# Upload CSV in Colab
from google.colab import files
uploaded = files.upload("file.csv")

# This won't work in Colab directly, instead:

a<-read.csv("C:\\Users\\91620\\OneDrive\\Desktop\\stud.csv")
print(a)
print(ncol(a))  # to know the column
print(nrow(a))  # to know the row
print(fix(a))   # to rewrite the file.csv
print(colname(a))
print(rowname(a))
barplot(data$Marks, names.arg = data$Name, col = "skyblue")

ERROR: Error in parse(text = input): <text>:8:6: unexpected symbol
7: # Upload CSV in Colab
8: from google.colab
        ^
